### ISSUE TITLE
What are the Three Arrows?

### ISSUE THREAD

**Issue by snowvix** [ironfront-usa/ironfront-usa.github.io#10]
write-up on what each of the 3 arrows means. antifascism, antiracism, and antiauthoritarian. "auth" includes authcomm, but not non-auth comms. 

delve into the history of each of those. reference old german iron front flyers and posters. compare them to our current ones. explain how the antimonarchist sentiments of one of the arrows was superseded by antiracist sentiments.

Pull to `./who/threearrows.md`

**Comment by Krat131** [comment]
"Three Arrows were designed so as to cover up a swastika, as well as represent the three main enemies of German Democracy; The Monarchists, the Soviets, and the Fascists. Our group is named after this group, as we aim to bring the same type of mass mobilization against fascism here in the United States."

**Comment by Krat131** [comment]
I think we can cover this in the FAQ
