### ISSUE TITLE
Contact info.

### ISSUE THREAD

**Issue by snowvix** [ironfront-usa/ironfront-usa.github.io#11]
little blurb about why and how to contact us. link to our email and the subreddit modmail. DO NOT give out individuals' contact information, including how to DM them.

Pull to `./get-involved/contact.md`

**Comment by snowvix** [comment]
perhaps embed a "send us an email!" form on the contact page?

**Comment by Krat131** [comment]
Email: American_Iron_Front@protonmail.com

**Comment by Krat131** [comment]
Twitter: @Iron_FrontUSA
