### ISSUE TITLE
Design a website banner.

### ISSUE THREAD

**Issue by snowvix** [ironfront-usa/ironfront-usa.github.io#19]
design a banner for the website. ideally in an .svg format. this banner will appear at the top of every page about the navbar (#17), and will have our full name "American Iron Front" logo overlaid on top of it. please share work in progress files in comments on this issue.

**Comment by Krat131** [comment]
![IRON FRONT banner](https://user-images.githubusercontent.com/63821547/82834484-3ed6d500-9e8f-11ea-8056-8afd2d0ed7f3.png)
