### ISSUE TITLE
Mission statement

### ISSUE THREAD

**Issue by snowvix** [ironfront-usa/ironfront-usa.github.io#3]
A brief (1-3 sentences) statement that will appear on our home page. Antifascist, Antiracist, Antiauthoritarian.

**Comment by Krat131** [comment]
The A.I.F is a decentralized activist group dedicated to combating fascism, racism, and authoritarianism in all its forms, as well as fight for a democracy that works for the well-being of all the American People, under which liberty and freedom are ensured for all, regardless of race, creed, gender, sexuality, or any other immutable trait.
